spring:
  #配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://120.79.138.220/gulimall_member?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
  cloud:
    nacos:
      discovery:
        server-addr: 120.79.138.220:8848 #nacos注册地址
  application:
    name: mall-coupon
#ORM设置
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml  #配置mybatisPlus的mapper.xml文件位子
  global-config:
    db-config:
      id-type: auto  #数据库的主键全部默认是自增
      logic-delete-value: 1   #逻辑已删除
      logic-not-delete-value: 0 #逻辑未删除

server:
  port: 7000 #端口设置


